# -*- coding: utf-8 -*-

from models import db, User, Requirement, Task, RequirementUsage


def recreate_database():
    db.connect()

    for table in [RequirementUsage, Task, User, Requirement]:
        try:
            db.drop_table(table)
        except:
            db.rollback()

    db.create_tables([User, Requirement, Task, RequirementUsage])

    Requirement.Add('Вы отвечаете на письмо.', 1, False)
    Requirement.Add('Вы на регистрации.', 1, True)
    Requirement.Add('Вы на секции "Управление разработкой".', 1, True)
    Requirement.Add('Вы на секции "FRONTTALKS".', 1, True)
    Requirement.Add('Вы на секции "SEVERSIDE. Experience".', 1, True)
    Requirement.Add('Вы на секции "SERVERSIDE. Knowlege".', 1, True)
    Requirement.Add('Вы на секции "Тестирование".', 1, True)
    Requirement.Add('Вы на секции "Системный анализ".', 1, True)
    Requirement.Add('Вы на секции "Дизайн".', 1, True)
    Requirement.Add('Вы в гардеробе.', 1, True)
    Requirement.Add('Вы на стоянке.', 1, True)
    Requirement.Add('Вы на улице.', 1, True)
    Requirement.Add('Вы на диване.', 1, True)
    Requirement.Add('Вы в планетарии.', 1, True)
    Requirement.Add('Вы на кухне.', 1, True)
    Requirement.Add('Изображаете известный логотип.', 2, False)
    Requirement.Add('Вы обнимаетесь.', 2, True)
    Requirement.Add('Вы управляете авто.', 2, True)
    Requirement.Add('Смотрите на звезды.', 2, True)
    Requirement.Add('Вы на обеде.', 2, True)
    Requirement.Add('Вы на кофе-брейке.', 2, True)
    Requirement.Add('Доклады начались, а вы до сих пор на кофе-брейке.', 2, True)
    Requirement.Add('Вы пригласили девочку айдеко на свидание в планетарий.', 2, True)
    Requirement.Add('Вы в планетарии и понятно, что земля плоская.', 2, True)
    Requirement.Add('Вы в позе собаки мордой вниз.', 2, True)
    Requirement.Add('Вы делаете лифто-лук.', 2, True)
    Requirement.Add('Вы делаете туалетный лук.', 2, True)
    Requirement.Add('Вы на Афтепати.', 3, True)
    Requirement.Add('вы во время доклада - вы докладчик, вас слушает не меньше 10 человек.', 5, True)
    Requirement.Add('Вы обмениваетесь визитками.', 1, False)
    Requirement.Add('Вы внимательно слушаете доклад.', 1, False)
    Requirement.Add('Вы пьете кофе.', 1, False)
    Requirement.Add('С вами в кадре 1 волонтер.', 1, False)
    Requirement.Add('Вы без обуви.', 1, False)
    Requirement.Add('Все в красном.', 1, False)
    Requirement.Add('Вы работаете.', 1, False)
    Requirement.Add('Вы читаете код.', 1, False)
    Requirement.Add('Все едят.', 1, False)
    Requirement.Add('Вам не хватило розетки паника паника.', 1, False)
    Requirement.Add('Вы радуетесь хорошему докладу.', 1, False)
    Requirement.Add('Все постят в твиттер.', 1, False)
    Requirement.Add('Вы оба в очках.', 1, False)
    Requirement.Add('Вы жонглируете тремя или более невидимыми предметами.', 1, False)
    Requirement.Add('Вы тестируете интерфейс.', 1, False)
    Requirement.Add('Вы проектируете пользовательский сценарий.', 1, False)
    Requirement.Add('Вы принимаете  задание у дизайнера.', 1, False)
    Requirement.Add('Вы чешете дизайнера за ушком.', 1, False)
    Requirement.Add('Вы используете стилус не по назначению.', 1, False)
    Requirement.Add('Скорбим по флешу публично.', 1, False)
    Requirement.Add('Вас штрафуют за превышение скорости.', 1, False)
    Requirement.Add('Вы в шлеме.', 1, False)
    Requirement.Add('Вы спите.', 1, False)
    Requirement.Add('Вы котик.', 1, False)
    Requirement.Add('Вас гладят.', 1, False)
    Requirement.Add('Вы сдаете куртку.', 1, False)
    Requirement.Add('Вы едите.', 1, False)
    Requirement.Add('Вы пьете.', 1, False)
    Requirement.Add('Вы бьете.', 1, False)
    Requirement.Add('Вы пишете в твиттер.', 1, False)
    Requirement.Add('Вы делаете дакфейс.', 1, False)
    Requirement.Add('К кадру применен эффект паралакc.', 1, False)
    Requirement.Add('У вас часы на обеих руках.', 1, False)
    Requirement.Add('Хлопают докладчику.', 2, False)
    Requirement.Add('Вы проводите mthen интервью.', 2, False)
    Requirement.Add('Вы задаете вопросы.', 2, False)
    Requirement.Add('С вами в кадре 1 докладчик.', 2, False)
    Requirement.Add('Вы меняетесь футболками.', 2, False)
    Requirement.Add('Все без обуви.', 2, False)
    Requirement.Add('Вы понимаете сервер.', 2, False)
    Requirement.Add('Вы меряетесь телефонами.', 2, False)
    Requirement.Add('Один из вас держит другого на руках.', 2, False)
    Requirement.Add('Вы нарисовали новый логотип для айтипипл.', 2, False)
    Requirement.Add('С вами в кадре есть сотрудники айтипипл.', 2, False)
    Requirement.Add('С вами в кадре арт директор негодует.', 2, False)
    Requirement.Add('Один из людей в кадре изображает пиктограмму гамбургер.', 2, False)
    Requirement.Add('Изобразите бинарное дерево из участников.', 2, False)
    Requirement.Add('Сфотографироваться с докладчиком секции "Управление разработкой".', 2, False)
    Requirement.Add('Сфотографироваться с докладчиком секции "FRONTTALKS".', 2, False)
    Requirement.Add('Сфотографироваться с докладчиком секции "SEVERSIDE. Experience".', 2, False)
    Requirement.Add('Сфотографироваться с докладчиком секции "SERVERSIDE. Knowlege".', 2, False)
    Requirement.Add('Сфотографироваться с докладчиком секции "Тестирование".', 2, False)
    Requirement.Add('Сфотографироваться с докладчиком секции "Системный анализ".', 2, False)
    Requirement.Add('Сфотографироваться с докладчиком секции "ДИЗАЙН".', 2, False)
    Requirement.Add('Вы сидите на докладе и демонстрируете, что это места для поцелуев.', 2, False)
    Requirement.Add('За секунду до столкновения.', 2, False)
    Requirement.Add('В кадре есть наклейка от айтипипл и все ее изображают.', 2, False)
    Requirement.Add('Вы в солнечных очках.', 2, False)
    Requirement.Add('Все на кортах и лузгают семки.', 2, False)
    Requirement.Add('Вы меняетесь одеждой.', 2, False)
    Requirement.Add('Вы берете в гардеробе бинокль.', 2, False)
    Requirement.Add('Вы задаете вопросы докуладчику.', 2, False)
    Requirement.Add('Докладчик вам отвечает.', 2, False)
    Requirement.Add('Вы и человек из  вашей компании.', 2, False)
    Requirement.Add('Эффект бесконечного зеркала.', 2, False)
    Requirement.Add('В кадре есть 5 строк на языке программирования го.', 2, False)
    Requirement.Add('В кадре видно, что ты коммитишь в репозиторий.', 2, False)
    Requirement.Add('В кадре видно мердж-конфликт.', 2, False)
    Requirement.Add('В кадре есть схема декомпозиции процесса выдачи бейджиков на дампе.', 2, False)
    Requirement.Add('Менеджер иллюстрирует участниками диаграмму ганта.', 2, False)
    Requirement.Add('Вы водопад.', 2, False)
    Requirement.Add('Вы гибкая разработка.', 2, False)
    Requirement.Add('У вас скайп колл, на экране видно что требования изменились.', 2, False)
    Requirement.Add('С вами кадре 5 волонтеров.', 3, False)
    Requirement.Add('В кадре n докладчиков, где n — простое число.', 3, False)
    Requirement.Add('Вы нашли 3 макбука и пытаетесь их поделить.', 3, False)
    Requirement.Add('Вы играете со шрифтами.', 3, False)
    Requirement.Add('С Вами в кадре есть 3 человека, они позируют для иконок.', 3, False)
    Requirement.Add('Из фото должно быть понятно чем HTML4 отличается от HTML5.', 3, False)
    Requirement.Add('Из фото должно быть понятно что такое монады.', 3, False)
    Requirement.Add('Из фото должно быть понятно что такое лямбда.', 3, False)
    Requirement.Add('Ко всем участникам в кадре применен эфеект мокрый пол.', 3, False)
    Requirement.Add('В кадре есть человек который хоть раз программировал на хаскель.', 3, False)
    Requirement.Add('Война между рубистами и питонистами.', 3, False)
    Requirement.Add('Все гнобят пхпешника.', 3, False)
    Requirement.Add('В кадре есть бизнес-ангел, вы договорились на инвестиции.', 3, False)
    Requirement.Add('В кадре интерфейс модератора в котором на проверке эта фотография.', 3, False)
    Requirement.Add('У вас 6 бутербродов, а кому-то не хватило.', 3, False)
    Requirement.Add('Вы разрубили что-то, что не должны были.', 3, False)
    Requirement.Add('Вы спорите о гелиоцентричности и доказываете что это ложная теория.', 3, False)
    Requirement.Add('В кадре три программиста спрашивают девушку из айдеко а можно девушек как в прошлом году.', 3, False)
    Requirement.Add('В кадре рассказывают с помощью наклеек айтипипл сюжет ромео и джульетту.', 3, False)
    Requirement.Add('Вы слепили из мякиша Apple-Watch.', 3, False)
    Requirement.Add('В кадре вы, буклет и девочки и они отеты в цвета буклета.', 3, False)
    Requirement.Add('В кадре есть три разных вида смарт вотчей.', 3, False)
    Requirement.Add('В кадре логотип джетстайла, но огонь настоящий.', 3, False)
    Requirement.Add('На фото должно  быть понятно что только что случился аякс.', 3, False)
    Requirement.Add('Из кадра должно быть понятно что такое рефакторинг и почему он важен.', 3, False)
    Requirement.Add('Вы используете шаблонизаторы или они вас.', 3, False)
    Requirement.Add('В кадре есть Internet Explorer 6 - у вас на компе.', 3, False)
    Requirement.Add('Вы тестируете вашу верстку сразу в 6 устройствах.', 3, False)
    Requirement.Add('Вы тестируете в 6 браузерах.', 3, False)
    Requirement.Add('Из кадра понтяно что такое бэм.', 3, False)
    Requirement.Add('В кадре прошло не меньше 100 зеленых тестов.', 3, False)
    Requirement.Add('В кадре есть  vml-диаграма  дампа.', 3, False)
    Requirement.Add('В кадре есть uml-диаграмма дампа.', 3, False)
    Requirement.Add('В кадре есть 3 менеджера, у них конфликт приоритетов.', 3, False)
    Requirement.Add('В кадре есть 1 менеджер и 3 разработчика.', 3, False)
    Requirement.Add('Менеджер фронтен бекенд тестировщик и дизайнер, они выстроены в порядке использования в диаграмме ганта.', 3, False)
    Requirement.Add('Все в кадре играют в планнинг покер.', 3, False)
    Requirement.Add('Изобразите как будто вы аджпайл.', 3, False)
    Requirement.Add('В кадре есть дедлайн и он просран.', 3, False)
    Requirement.Add('В кадре есть канбан доска, в которой вы планируете этот кадр.', 3, False)
    Requirement.Add('У вас скайп колл и ваш собеседник негр это видно.', 3, False)
    Requirement.Add('В кадре 8 очкариков.', 5, False)
    Requirement.Add('У вас больше 5 устройств  эппл и вы пользуетесь всеми прямо сейчас.', 3, False)
    Requirement.Add('В кадре менеджер ставит задачу и понятно почему она поставлена плохо.', 3, False)
    Requirement.Add('В кадре менеджер и разработчик спорят об эстимейте задачи демонстрируя аргументы.', 3, False)
    Requirement.Add('В кадре 5 человек пьют кофе - остальным не хватило.', 4, False)
    Requirement.Add('Изобразите легаси код.', 4, False)
    Requirement.Add('В кадре 4 волонтера, у них не хватает пальцев чтобы сосчитать баги которые есть в кадре.', 4, False)
    Requirement.Add('Вы собираете требования, и они слишком противоречивы.', 4, False)
    Requirement.Add('Эффект бесконечного зеркала.', 5, False)
    Requirement.Add('Менеджер рубит косты саблей.', 5, False)
    Requirement.Add('С вами взаимодействуют как будто вы отзывчивый интерфейс.', 5, False)
    Requirement.Add('В кадре три менеджера на коленях умоляют разработчика выйти в ночь.', 5, False)
    Requirement.Add('В кадре есть аккаунт на гитхабе и у него 50 фоловеров.', 7, False)
    Requirement.Add('В кадре 7 докладчиков все из разных секций.', 10, False)
    Requirement.Add('Все в рубашках в клеточку.', 1, False)
    Requirement.Add('Вы оба в пиджаках.', 2, False)
    Requirement.Add('В кадре сисадмин бьет в бубен.', 3, False)
    Requirement.Add('В кадре бородач.', 2, False)
    Requirement.Add('Вы оба танцуете.', 2, False)
    Requirement.Add('В кадре плюшевая игрушка.', 2, False)
    Requirement.Add('Вы играете в гляделки.', 1, False)
    Requirement.Add('Вы показываете друг другу язык.', 1, False)
    Requirement.Add('Вы ставите друг другу рожки.', 1, False)
    Requirement.Add('Вы кладете два айфона в тостеры для зарядки.', 4, True)
    Requirement.Add('На фото видно инстаграмм, на котором тоже самое фото.', 4, True)
    Requirement.Add('На фото видно твиттер, в котором тоже фото выложен с хештегом #селфидамп.', 4, True)
    Requirement.Add('На фото видно, что вы организовали настоящую скрам-команду.', 3, True)
    Requirement.Add('Вы гуру парного программирования.', 3, True)
    Requirement.Add('Вы отжимаетесь на физ-ре.', 3, True)
    Requirement.Add('Вы оба в больших наушниках.', 2, False)
    Requirement.Add('Вы лошадь и всадник.', 3, True)
    Requirement.Add('Вы закрываете глаза на мелкие недочеты.', 2, False)

    User.add('Александр Абрамович', '', False)
    User.add('Борис Бурда', 'Яндекс', False)
    User.add('Василий Венедиктов', 'JetStyle', False)
    User.add('Дмитрий Дыров', 'СКБ Контур', False)
    User.add('Валерий Порча', 'Наумен', False)
    User.add('Николай Комаров', 'microsoft', False)
    User.add('Елена Куравлёва', 'microsoft', False)
    User.add('Иван Водопьянов', 'Предприниматель', False)
    User.add('Илья Мурманский', 'Сбербанк', False)
    User.add('Лёха Кофман', 'Дойче', True)
    User.add('Лёха Кирпичников', 'СКБ Контур', True)
    User.add('Таня Кирпичникова', 'JetStyle', True)

    db.close()


if __name__ == '__main__':
    recreate_database()
