# -*- coding: utf-8 -*-

from models import db, User, Requirement, Task, RequirementUsage


def recreate_database():
    db.connect()

    for table in [RequirementUsage, Task, User, Requirement]:
        try:
            db.drop_table(table)
        except:
            db.rollback()

    db.create_tables([User, Requirement, Task, RequirementUsage])

    Requirement.add('Вы отвечаете на письмо, не обязательно электронное.', 1, False)
    Requirement.add('Вы пришли на стойку регистрации за бейджами.', 1, True)
    Requirement.add('Вы на секции "Управление разработкой".', 1, True)
    Requirement.add('Вы на секции "FRONTTALKS".', 1, True)
    Requirement.add('Вы на секции "SEVERSIDE.Experience".', 1, True)
    Requirement.add('Вы на секции "SERVERSIDE.Knowledge".', 1, True)
    Requirement.add('Вы на секции "Тестирование".', 1, True)
    Requirement.add('Вы на секции "Системный анализ".', 1, True)
    Requirement.add('Вы на секции "Дизайн".', 1, True)
    Requirement.add('Вы сдаете в гардероб свое лучшее пальто.', 1, True)
    Requirement.add('Вы на стоянке возле мерседеса (еще лучше, если это ваш).', 1, True)
    Requirement.add('Вы на улице, где сегодня заметно потеплело.', 1, True)
    Requirement.add('Вы проверяете, удобные ли на конференции диваны.', 1, True)
    Requirement.add('It\'s... beautiful... (вы в планетарии).', 1, True)
    Requirement.add('Вы на кухне, хотя суточную норму калорий уже превысили.', 1, True)
    Requirement.add('Вы изображаете какой-нибудь известный логотип.', 2, False)
    Requirement.add('Вы обнимаетесь друг с другом.', 2, True)
    Requirement.add('Вы управляете чужим автомобилем.', 2, True)
    Requirement.add('Вы смотрите на звезды.', 2, True)
    Requirement.add('Вы на обеде, и на нем интереснее, чем на докладах.', 2, True)
    Requirement.add('Доклады начались, а вы до сих пор на кофе-брейке.', 2, True)
    Requirement.add('Вы пригласили девочку Ideco на свидание в планетарий.', 2, True)
    Requirement.add('Вы в сходили в планетарий и поняли, что Земля плоская.', 2, True)
    Requirement.add('Вы делаете лифтолук лучше Ксении Собчак.', 2, True)
    Requirement.add('Вы делаете туалетный лук лучше Ким Кардашьян.', 2, True)
    Requirement.add('Вы на афтепати - делаете то, что обычно делают на афтепати.', 3, True)
    Requirement.add('Вы докладчики, вас слушает не меньше 10 человек.', 5, True)
    Requirement.add('Вы обмениваетесь визитками.', 1, False)
    Requirement.add('Вы внимательно слушаете доклад.', 1, False)
    Requirement.add('С вами в кадре волонтер, которого уже достали такие как вы с фотографированием.', 1, False)
    Requirement.add('Вы без обуви, не застудите ноги.', 1, False)
    Requirement.add('В кадре все в красной одежде.', 1, False)
    Requirement.add('Вы же сидите работаете, зачем вы вообще приехали на конференцию?', 1, False)
    Requirement.add('Вы читаете хорошо отрефакторенный код.', 1, False)
    Requirement.add('В кадре все едят.', 1, False)
    Requirement.add('Вам не хватило розетки, но никто не сочувствует.', 1, False)
    Requirement.add('Вы радуетесь хорошему докладу.', 1, False)
    Requirement.add('Все постят в твиттер.', 1, False)
    Requirement.add('Вы оба в очках.', 1, False)
    Requirement.add('Вы жонглируете тремя или более невидимыми предметами.', 1, False)
    Requirement.add('Вы тестируете интерфейс.', 1, False)
    Requirement.add('Вы проектируете пользовательский сценарий.', 1, False)
    Requirement.add('Вы принимаете задание у дизайнера.', 1, False)
    Requirement.add('Вы чешете дизайнера за ушком.', 1, False)
    Requirement.add('Вы используете стилус не по назначению.', 2, False)
    Requirement.add('Вас штрафуют за превышение скорости.', 1, False)
    Requirement.add('Вы в шлеме.', 1, False)
    Requirement.add('Вы спите.', 1, False)
    Requirement.add('Вы котики, вас гладят.', 1, False)
    Requirement.add('Вы делаете дакфейс не хуже Тейлор Свифт.', 1, False)
    Requirement.add('Примените к кадру эффект параллакc.', 1, False)
    Requirement.add('У вас часы на обеих руках.', 1, False)
    Requirement.add('Вы яростно хлопаете докладчику с каменным лицом.', 2, False)
    Requirement.add('Вы проводите интервью - но в качестве микрофона у вас что-то неуместное, вроде банана.', 2, False)
    Requirement.add('С вами в кадре докладчик, которого уже достали такие как вы с фотографированием.', 2, False)
    Requirement.add('Вы меняетесь футболками с таким же энтузиазмом, как футболисты ярославского Шинника после матча с Барселоной.', 2, False)
    Requirement.add('Вы затерминалились на сервер с FreeBSD.', 2, False)
    Requirement.add('Вы меряетесь телефонами.', 2, False)
    Requirement.add('Один из вас держит другого на руках.', 2, False)
    Requirement.add('Вы нарисовали новый логотип для IT-People, и он лучше старого.', 2, False)
    Requirement.add('С вами в кадре есть сотрудники IT-People, которых уже достали такие как вы с фотографированием.', 2, False)
    Requirement.add('С вами в кадре арт-директор, и он негодует.', 2, False)
    Requirement.add('Один из людей в кадре изображает пиктограмму "гамбургер".', 2, False)
    Requirement.add('Изобразите бинарное дерево из участников.', 2, False)
    Requirement.add('Фото с докладчиком секции "Управление разработкой".', 2, False)
    Requirement.add('Фото с докладчиком секции "FRONTTALKS".', 2, False)
    Requirement.add('Фото с докладчиком секции "SEVERSIDE. Experience".', 2, False)
    Requirement.add('Фото с докладчиком секции "SERVERSIDE. Knowlege".', 2, False)
    Requirement.add('Фото с докладчиком секции "Тестирование".', 2, False)
    Requirement.add('Фото с докладчиком секции "Системный анализ".', 2, False)
    Requirement.add('Фото с докладчиком секции "Дизайн".', 2, False)
    Requirement.add('Вы сидите на докладе на местах для поцелуев и пользуетесь этим.', 2, False)
    Requirement.add('Фото за секунду до столкновения.', 2, False)
    Requirement.add('Вы в солнечных очках.', 2, False)
    Requirement.add('Все на кортах и лузгают семки.', 2, False)
    Requirement.add('Вы берете в гардеробе бинокль.', 2, False)
    Requirement.add('Вы задаете вопросы докладчику.', 2, False)
    Requirement.add('Докладчик вам отвечает.', 2, False)
    Requirement.add('Вы и человек из вашей компании.', 2, False)
    Requirement.add('В кадре есть 5 строк на языке программирования Go.', 2, False)
    Requirement.add('В кадре видно, что ты коммитишь в репозиторий.', 2, False)
    Requirement.add('В кадре видно мердж-конфликт.', 2, False)
    Requirement.add('Менеджер иллюстрирует участниками диаграмму Ганта.', 2, False)
    Requirement.add('С вами кадре 5 волонтеров, которых уже достали такие как вы с фотографированием.', 3, False)
    Requirement.add('В кадре n докладчиков, где n - простое число больше единицы.', 3, False)
    Requirement.add('Вы нашли 3 макбука и пытаетесь их поделить (по-честному).', 3, False)
    Requirement.add('Вы играете со шрифтами.', 3, False)
    Requirement.add('С вами в кадре есть 3 человека, они позируют для иконок.', 3, False)
    Requirement.add('Из фото должно быть понятно чем CSS3 отличается от HTML5.', 3, False)
    Requirement.add('Из фото должно быть понятно что такое монады.', 3, False)
    Requirement.add('Из фото должно быть понятно что такое лямбда-исчисление.', 3, False)
    Requirement.add('Ко всем участникам в кадре применен эффект "мокрый пол".', 3, False)
    Requirement.add('В кадре есть человек который хоть раз программировал на Haskell.', 3, False)
    Requirement.add('На фото война между рубистами и питонистами.', 3, False)
    Requirement.add('Все гнобят пхпешника.', 3, False)
    Requirement.add('В кадре есть бизнес-ангел, который дает вам инвестиции наличными.', 3, False)
    Requirement.add('У вас 6 бутербродов с кофе-брейка, а кому-то их не хватило.', 3, False)
    Requirement.add('Упс: вы разрубили саблей что-то, что не должны были.', 3, False)
    Requirement.add('Вы слепили из мякиша Apple Watch.', 3, False)
    Requirement.add('В кадре есть три разных вида смартвотчей.', 3, False)
    Requirement.add('В кадре логотип JetStyle, но огонь настоящий.', 3, False)
    Requirement.add('Из кадра должно быть понятно, что такое рефакторинг, и почему он важен.', 3, False)
    Requirement.add('Вы используете шаблонизаторы (или они - вас).', 3, False)
    Requirement.add('В кадре есть Internet Explorer 6 - установлен у вас на компе.', 3, False)
    Requirement.add('Вы тестируете верстку сразу в 6 устройствах.', 3, False)
    Requirement.add('Вы тестируете в 6 браузерах.', 3, False)
    Requirement.add('Из кадра понтяно, что такое БЭМ.', 3, False)
    Requirement.add('В кадре ваши юнит-тесты, и не меньше ста из них зеленые.', 3, False)
    Requirement.add('В кадре есть uml-диаграмма ДАМПа.', 3, False)
    Requirement.add('В кадре есть 3 менеджера, у них конфликт приоритетов.', 3, False)
    Requirement.add('В кадре есть 1 менеджер и 3 разработчика.', 3, False)
    Requirement.add('В кадре менеджер, фронтенд-разработчик, бекенд-разработчик, тестировщик и дизайнер, и они выстроены в порядке использования в диаграмме Ганта.', 3, False)
    Requirement.add('Все в кадре играют в планнинг покер.', 3, False)
    Requirement.add('Изобразите, как будто вы agile.', 3, False)
    Requirement.add('В кадре есть дедлайн, и он просран.', 3, False)
    Requirement.add('В кадре есть канбан доска, в которой вы планируете этот кадр.', 3, False)
    Requirement.add('У вас скайп-колл, и ваш собеседник негр.', 3, False)
    Requirement.add('В кадре 8 очкариков.', 5, False)
    Requirement.add('У вас больше 5 устройств Apple, и вы пользуетесь всеми прямо сейчас.', 3, False)
    Requirement.add('Изобразите легаси код.', 4, False)
    Requirement.add('В кадре 4 волонтера, у них не хватает пальцев, чтобы сосчитать баги, которые тоже в кадре.', 4, False)
    Requirement.add('Вы собираете требования, и они слишком противоречивы.', 4, False)
    Requirement.add('Эффект бесконечного зеркала.', 5, False)
    Requirement.add('Менеджер рубит косты саблей.', 5, False)
    Requirement.add('С вами взаимодействуют, как будто вы отзывчивый интерфейс.', 5, False)
    Requirement.add('В кадре три менеджера на коленях умоляют разработчика выйти в ночь.', 5, False)
    Requirement.add('В кадре есть аккаунт на гитхабе и у него 50 фоловеров.', 7, False)
    Requirement.add('В кадре 7 докладчиков, все из разных секций.', 10, False)
    Requirement.add('Все в рубашках в клеточку.', 1, False)
    Requirement.add('Вы оба в пиджаках.', 2, False)
    Requirement.add('В кадре сисадмин бьет в бубен.', 3, False)
    Requirement.add('В кадре бородач, но его зовут не Алексей.', 2, False)
    Requirement.add('Вы оба танцуете.', 2, False)
    Requirement.add('В кадре плюшевая игрушка.', 2, False)
    Requirement.add('Вы играете в гляделки.', 1, False)
    Requirement.add('Вы показываете друг другу язык.', 1, False)
    Requirement.add('Вы ставите друг другу рожки.', 1, False)
    Requirement.add('Вы кладете два айфона в тостеры для зарядки.', 4, True)
    Requirement.add('На фото видно инстаграм, на котором то же самое фото.', 4, True)
    Requirement.add('На фото видно твиттер, в котором фото выложено с хештегом #селфидамп.', 4, True)
    Requirement.add('На фото видно, что вы организовали настоящую скрам-команду.', 3, True)
    Requirement.add('Вы гуру парного программирования.', 3, True)
    Requirement.add('Вы смогли отжаться 30 раз (мы все равно не верим).', 3, True)
    Requirement.add('Вы оба в больших наушниках.', 2, False)
    Requirement.add('Вы лошадь и всадник.', 3, True)
    Requirement.add('Вы закрываете глаза на мелкие недочеты.', 2, False)

    User.add('Александр Абрамович', '', False)
    User.add('Борис Бурда', 'Яндекс', False)
    User.add('Василий Венедиктов', 'JetStyle', False)
    User.add('Дмитрий Дыров', 'СКБ Контур', False)
    User.add('Валерий Порча', 'Наумен', False)
    User.add('Николай Комаров', 'microsoft', False)
    User.add('Елена Куравлёва', 'microsoft', False)
    User.add('Иван Водопьянов', 'Предприниматель', False)
    User.add('Илья Мурманский', 'Сбербанк', False)
    User.add('Лёха Кофман', 'Дойче', True)
    User.add('Лёха Кирпичников', 'СКБ Контур', True)
    User.add('Таня Кирпичникова', 'JetStyle', True)

    db.close()


if __name__ == '__main__':
    recreate_database()
