# -*- coding: utf-8 -*-

from models import db, User, Requirement, Task, RequirementUsage


def recreate_database():
    db.connect()

    for table in [RequirementUsage, Task, User, Requirement]:
        try:
            db.drop_table(table)
        except:
            db.rollback()

    db.create_tables([User, Requirement, Task, RequirementUsage])

    # Requirement.add('Вы отвечаете на письмо, не обязательно электронное.', 2, False)
    # Requirement.add('Вы пришли на стойку регистрации за бейджами.', 2, True)
    # Requirement.add('Вы на секции "Управление разработкой".', 1, True)
    # Requirement.add('Вы на секции "FRONTTALKS".', 1, True)
    # Requirement.add('Вы на секции "SEVERSIDE.Experience".', 1, True)
    # Requirement.add('Вы на секции "SERVERSIDE.Knowledge".', 1, True)
    # Requirement.add('Вы на секции "Тестирование".', 1, True)
    # Requirement.add('Вы на секции "Системный анализ".', 1, True)
    # Requirement.add('Вы на секции "Дизайн".', 1, True)
    # Requirement.add('Вы сдаете в гардероб свое лучшее пальто.', 2, True)
    # Requirement.add('Вы на стоянке возле мерседеса (еще лучше, если это ваш).', 4, True)
    # Requirement.add('Вы на улице, где сегодня заметно потеплело.', 3, True)
    # Requirement.add('Вы проверяете, удобные ли на конференции диваны.', 1, True)
    # Requirement.add('It\'s... beautiful... (вы в планетарии).', 3, True)
    # Requirement.add('Вы на кухне, хотя суточную норму калорий уже превысили.', 1, True)
    # Requirement.add('Вы изображаете какой-нибудь известный логотип.', 2, False)
    # Requirement.add('Вы обнимаетесь друг с другом.', 1, False)
    # Requirement.add('Вы управляете чужим автомобилем.', 2, True)
    # Requirement.add('Вы смотрите на звезды.', 2, False)
    # Requirement.add('Доклады начались, а вы до сих пор на кофе-брейке.', 3, True)
    # Requirement.add('Вы пригласили девочку из Ideco на свидание в планетарий.', 5, True)
    # Requirement.add('Вы в сходили в планетарий и поняли, что Земля плоская.', 2, True)
    # Requirement.add('Вы делаете лифтолук лучше Ксении Собчак.', 4, True)
    # Requirement.add('Вы делаете туалетный лук лучше Ким Кардашьян.', 3, True)
    # Requirement.add('Вы на афтепати - делаете то, что обычно делают на афтепати.', 3, True)
    # Requirement.add('Вы докладчики, вас слушает не меньше 10 человек.', 3, False)
    # Requirement.add('Вы обмениваетесь визитками.', 1, False)
    # Requirement.add('Вы внимательно слушаете доклад.', 2, False)
    # Requirement.add('С вами в кадре волонтер, которого уже достали такие как вы с фотографированием.', 2, False)
    # Requirement.add('Вы без обуви, не застудите ноги.', 1, False)
    # Requirement.add('В кадре все в красной одежде.', 4, False)
    # Requirement.add('Вы же сидите работаете, зачем вы вообще приехали на конференцию?', 5, False)
    # Requirement.add('Вы читаете хорошо отрефакторенный код.', 2, False)
    # Requirement.add('В кадре все едят.', 3, False)
    # Requirement.add('Вам не хватило розетки, но никто не сочувствует.', 2, False)
    # Requirement.add('Вы радуетесь хорошему докладу.', 1, False)
    # Requirement.add('Все постят в твиттер.', 1, False)
    # Requirement.add('Вы оба в очках.', 1, False)
    # Requirement.add('Вы жонглируете тремя или более невидимыми предметами.', 1, False)
    # Requirement.add('Вы тестируете интерфейс.', 2, False)
    # Requirement.add('Вы проектируете пользовательский сценарий.', 2, False)
    # Requirement.add('Вы принимаете задание у дизайнера.', 2, False)
    # Requirement.add('Вы чешете дизайнера за ушком.', 2, False)
    # Requirement.add('Вы используете стилус не по назначению.', 3, False)
    # Requirement.add('Вас штрафуют за превышение скорости.', 3, False)
    # Requirement.add('Вы в шлеме.', 3, False)
    # Requirement.add('Вы спите.', 1, False)
    # Requirement.add('Вы котики, вас гладят.', 2, False)
    # Requirement.add('Вы делаете дакфейс не хуже Тейлор Свифт.', 1, False)
    # Requirement.add('У вас часы на обеих руках.', 2, False)
    # Requirement.add('Вы яростно хлопаете докладчику с каменным лицом.', 1, False)
    # Requirement.add('Вы проводите интервью - но в качестве микрофона у вас что-то неуместное.', 2, False)
    # Requirement.add('С вами в кадре докладчик, которого уже достали такие как вы с фотографированием.', 3, False)
    # Requirement.add('Вы меняетесь футболками с таким же энтузиазмом, как футболисты ярославского Шинника после матча с Барселоной.', 5, False)
    # Requirement.add('Вы затерминалились на сервер с FreeBSD.', 3, False)
    # Requirement.add('Вы меряетесь телефонами.', 1, False)
    # Requirement.add('Один из вас держит другого на руках.', 2, False)
    # Requirement.add('Вы нарисовали новый логотип для IT-People, и он лучше старого.', 3, False)
    # Requirement.add('С вами в кадре есть сотрудники IT-People, которых уже достали такие как вы с фотографированием.', 3, False)
    # Requirement.add('Один из людей в кадре изображает пиктограмму "гамбургер".', 2, False)
    # Requirement.add('Изобразите бинарное дерево из участников.', 2, False)
    # Requirement.add('Фото с докладчиком секции "Управление разработкой".', 3, True)
    # Requirement.add('Фото с докладчиком секции "FRONTTALKS".', 3, True)
    # Requirement.add('Фото с докладчиком секции "SEVERSIDE. Experience".', 3, True)
    # Requirement.add('Фото с докладчиком секции "SERVERSIDE. Knowlege".', 3, True)
    # Requirement.add('Фото с докладчиком секции "Тестирование".', 3, True)
    # Requirement.add('Фото с докладчиком секции "Системный анализ".', 3, True)
    # Requirement.add('Фото с докладчиком секции "Дизайн".', 3, True)
    # Requirement.add('Вы сидите на докладе на местах для поцелуев и пользуетесь этим.', 3, True)
    # Requirement.add('Фото за секунду до столкновения.', 3, False)
    # Requirement.add('Вы в солнечных очках.', 5, False)
    # Requirement.add('Все на кортах и лузгают семки.', 2, True)
    # Requirement.add('Вы берете в гардеробе бинокль.', 3, True)
    # Requirement.add('Вы задаете вопросы докладчику.', 3, True)
    # Requirement.add('В кадре есть 5 строк на языке программирования Go.', 3, False)
    # Requirement.add('В кадре видно, что ты коммитишь в репозиторий.', 3, False)
    # Requirement.add('В кадре видно мердж-конфликт.', 4, False)
    # Requirement.add('Менеджер составляет диаграмму Ганта из участников.', 5, True)
    # Requirement.add('С вами кадре 5 волонтеров, которых уже достали такие как вы с фотографированием.', 6, True)
    # Requirement.add('В кадре n докладчиков, где n - простое число.', 4, True)
    # Requirement.add('Вы нашли 3 макбука и пытаетесь их поделить (по-честному).', 4, True)
    # Requirement.add('Вы нашли 11 телефонов и пытаетесь их поделить (по-честному).', 4, True)
    # Requirement.add('Вы играете со шрифтами.', 3, False)
    # Requirement.add('Из фото должно быть понятно, чем CSS3 отличается от HTML5.', 3, False)
    # Requirement.add('Все гнобят пхпешника.', 3, False)
    # Requirement.add('В кадре есть бизнес-ангел, который дает вам инвестиции наличными.', 2, False)
    # Requirement.add('У вас 6 бутербродов с кофе-брейка, а кому-то их не хватило.', 4, True)
    # Requirement.add('Упс: вы разрубили саблей что-то, что не должны были.', 4, True)
    # Requirement.add('Вы слепили из мякиша Apple Watch.', 6, False)
    # Requirement.add('В кадре логотип JetStyle.', 1, False)
    # Requirement.add('В кадре логотип JetStyle, но огонь настоящий.', 2, False)
    # Requirement.add('Из кадра должно быть понятно, что такое рефакторинг, и почему он важен.', 4, False)
    # Requirement.add('Вы тестируете верстку сразу в 6 устройствах.', 4, False)
    # Requirement.add('В кадре ваши юнит-тесты, и не меньше ста из них зеленые.', 5, False)
    # Requirement.add('В кадре есть 3 менеджера, у них конфликт приоритетов.', 2, False)
    # Requirement.add('В кадре есть 1 менеджер и 3 разработчика.', 2, False)
    # Requirement.add('Вы играете в планнинг покер.', 3, False)
    # Requirement.add('Вы меряетесь, кто более agile.', 2, False)
    # Requirement.add('В кадре есть дедлайн, и он просран.', 2, False)
    # Requirement.add('В кадре есть канбан доска, в которой вы планируете этот кадр.', 5, True)
    # Requirement.add('У вас скайп-колл, и ваш собеседник негр.', 4, True)
    # Requirement.add('В кадре 8 очкариков.', 6, False)
    # Requirement.add('У вас больше 5 устройств Apple, и вы пользуетесь всеми прямо сейчас.', 4, False)
    # Requirement.add('Эффект бесконечного зеркала.', 6, False)
    # Requirement.add('Менеджер рубит косты саблей.', 5, False)
    # Requirement.add('С вами взаимодействуют, как будто вы отзывчивый интерфейс.', 5, False)
    # Requirement.add('В кадре три менеджера на коленях умоляют разработчика выйти в ночь.', 3, False)
    # Requirement.add('В кадре 7 докладчиков, все из разных секций.', 8, True)
    # Requirement.add('Все в рубашках в клеточку.', 3, False)
    # Requirement.add('Вы оба в пиджаках.', 4, False)
    # Requirement.add('В кадре сисадмин бьет в бубен.', 3, False)
    # Requirement.add('В кадре три бородача.', 4, False)
    # Requirement.add('Вы оба танцуете.', 2, False)
    # Requirement.add('В кадре плюшевая игрушка.', 4, False)
    # Requirement.add('Вы показываете друг другу язык.', 1, False)
    # Requirement.add('Вы ставите друг другу рожки.', 1, False)
    # Requirement.add('Вы кладете два айфона в тостеры для зарядки.', 2, True)
    # Requirement.add('На фото видно инстаграм, на котором то же самое фото.', 4, True)
    # Requirement.add('На фото видно твиттер, в котором фото выложено с хештегом #селфидамп.', 4, True)
    # Requirement.add('На фото видно, что вы организовали настоящую скрам-команду.', 3, True)
    # Requirement.add('Вы гуру парного программирования.', 2, False)
    # Requirement.add('Вы смогли отжаться 30 раз (мы все равно не верим).', 1, True)
    # Requirement.add('Вы оба в больших наушниках.', 2, False)
    # Requirement.add('Вы лошадь и всадник.', 2, True)
    # Requirement.add('Вы в кресле-мешке.', 1, True)

    # User.add('Алексей Кофман', 'Организатор', True)
    # User.add('Алексей Кирпичников', 'СКБ Контур', True)
    # User.add('Сергей Васильев', 'Организатор', True)
    # User.add('Таня Кирпичникова', 'JetStyle', True)
    # User.add('Аня Татьянкина', 'JetStyle', True)

    db.close()


if __name__ == '__main__':
    recreate_database()
